### ISSUE TITLE
hasOne type of relationship between Post and Author

### ISSUE THREAD

**Issue by ghost** [brettshollenberger/ActiveResource#10]
Hey, had been checking out your original Active Resource, and accidentally found this one. Seems like you've been working quite hard on this one. Interested if you're going to keep working on this one and finally give it a more public name?

Not sure if issue's are welcome, but I'm into this new lib your'e making and I have a lot of questions. Well one at a time..

So I have a Post model:

```
        Post.inherits(ngActiveResource.Base);

        function Post() {
            this.string('title');
            this.string('body');
            this.string('postedOn');

            this.integer('authorId');
        };

        Post.hasMany('comments');
        Post.hasMany('categories');

        Post.api.configure(function (config) {
            config.resource = "posts";
        });

        Post.validates({
            title: { required: true },
            body: { length: { min: 100 } }
        });
```

And an Author model:

```
        Author.inherits(ngActiveResource.Base);

        function Author() {

            this.string('firstName');
            this.string('lastName');

            this.computedProperty("fullName", function () {
                return this.firstName + " " + this.lastName;
            }, ["firstName", "lastName"]);
        };

        Author.hasMany('posts');
        Author.hasMany('comments');

        Author.api.configure(function (config) {
            config.resource = "authors";
        });
```

Now I couldn't find an easy way to define Post.author. Of course somePost.author = Author.find(somePost.authorId) works, but that is just defining author property on Post model later on when you need to load author, and it's not a part of Model definition process, like hasMany and belongsTo is. It would be neat to have something like:

```
       Post.hasOne('author', {keyOfAuthorOnPost: 'authorId'});
```

And when you want to load author from server, you could just:

```
       Post.author.find(); //Returns single item, and author is not a collection
```

So it would work something like findAll with collections:

```
       post.comments.findAll()
```

Any suggestions? Been trying everything with belongsTo and hasMany relations, but I can't get anything elegant going on. Also defining Author.hasMany('post') doesnt seem to create an inverse relation on Post (Post.author doesn't exist).

**Comment by steveoliver** [comment]
Indeed, the hasMany (all associations?) which previously worked (with FacultyCreative/ngActiveResource), now no longer work.  I've been trying to debug why, but I do know there are no API calls for i.e. /api/comments?post_id=X when I have a similar model(s) Post <-- Comments / Authors.  ping @brettshollenberger.

**Comment by brettshollenberger** [comment]
Hey guys,
@Mariusha thanks for lighting something up back here--I originally planned for this to be an official release on the other page, but that company is dead and I had difficulty getting ahold of anyone to hand over the rights to the repo.

Barring that, the APIs on this one are ready to go (I've used this version on projects myself lately). @steveoliver, understanding that there are breaking changes between this and the previous version. 

It sounds to me like you have a `hasMany/belongsTo` relationship between authors and posts, right? In this case the `hasOne` would have the same effect as the `belongsTo`. The `hasOne` relationship was really just a one-to-one relationship, which still ought to be added here.

In terms of the actual accessor method being used in the way you described (`post.author.find()`), I grappled with a solution like this for a while. The problem with the solution is that Javascript's `undefined`s cannot have methods of their own. So when `post.author` is undefined, you will have a hard time calling `find` on it.

One possible solution is the NullObject pattern, but it is not very widely used in Javascript. I figured that more developers would want to check for `undefined`s and write finders in the way you described than the other way around. A NullObject obviously would not be undefined, and it would not integrate well with lots of popular libraries like Underscore, Lodash, jQuery, etc, which don't have a good pattern for nil checking (like Ruby's `.nil?`).

My official suggestion at the moment would be to write a finder on your class if you're reusing this functionality a lot:

``` javascript
Post.findAuthor = function() {
  Author.find(post.authorId);
}
```

In response to @steveoliver's point, I decided to remove a lot of "magic" in this version in favor of (making API calls for you to load associations) because I could not adequately predict the most efficient way to retrieve your data for you. Less magic, more flexibility, better performance. Here's an example:

```
// Example 1:
// you load all your comments, and then all of the associated posts one at a time
angular.controller("CommentIndexCtrl", function(Post, Comment, $scope) {
   $scope.comments = Comment.where({per_page: 20});

  // Behind the scenes in this old version, I was effectively saying:
  //    $scope.comments.each(function(comment) {
  //       Post.find(comment.post_id);
  //    });
  //
  // That's one request for every single post! Not efficient, but the only way I can be sure
  // to get what you need.
})

// Example 2:
// you load all your comments, then all posts associated with those comments with your special endpoint
angular.controller("PostsIndexCtrl", function(Post, Comment, $scope) {
   $scope.posts = Post.where({per_page: 20}).then(function() {
      // you have an endpoint that will find comma-separated ids: "1,5,20,45"
      Comment.where({id: $scope.posts.pluck("id").join(",")});
   })

  // Since we have these cached locally after they're found by ID, we won't have to make a remote
  // request to view the data
})
```

**Comment by steveoliver** [comment]
Thanks, Brett.  I understand why you would leave loading of each resource down to each implementation.  That's what I was hoping you would say--it was be design that no API calls are made automagically.

I'm ok with null object checking (I think), but I'm still trying to understand how to populate the post.comments property not on-demand, but manually, i.e. after loading both Post and Comment with the nested where({}) calls in Example 2.  Once I have made both Post.where() and Comment.where(), [how] do I populate the post.comments and comment.post properties on each model instance?  I thought this was what ngActiveResource would be expected to do, but maybe that's now up to implementations of Post.after('where') and/or Comment.after('where') ?

**Comment by steveoliver** [comment]
To follow up from my previous comment:

Yes, ngActiveResource properly makes the associations, populating the Post object on Comments and comments array on Post, after doing two simple nested API calls, like this:

```
Post.where({ gid: groupId }).then(function(posts) {
  var nids = _.pluck(posts, 'nid').join(',').replace(/^,+|,+$/gm, '');
  Comment.where({ nid: nids });
});
```

AND

```
Post.after('where', function(posts) {
  $scope.posts = posts;
});
```

Note: the .replace exists to remove the trailing comma from the nids argument.
The Post.after('where') was the only way I could set $scope.posts. The direct assignment of $scope.posts = Post.where()... did not work. (Neither of these worked:)

```
$scope.posts = Post.where().then(function() {
  ...
});
```

```
Post.where().then(function(posts) {
  $scope.posts = posts;
  ...
});
```

I can work with this, but maybe I'm doing somethin wrong here. I'd like to know what you think of this, @brettshollenberger.

With some minor issues such as the one above, and some API changes (for the better), overall ngActiveResource here works as expected.

Thanks, Brett!  Awesome work!

**Comment by brettshollenberger** [comment]
Query functions in this version work a little different from the previous version.

They return a deferred collection, which can call the `$q` methods on itself.

So for instance, you could do:

``` javascript
$scope.posts = Post.where({ gid: groupId });

$scope.posts.then(function(posts) {
  var nids = _.pluck(posts, 'nid').join(',').replace(/^,+|,+$/gm, '');
  Comment.where({ nid: nids });
});
```

It was a little nicer than always having to assign via the callback, but I hadn't noticed some of these other bugs with the approach. Anyone that wants to work on refactoring is welcome :)
